### ISSUE TITLE
bail out after first failed test

### ISSUE THREAD

**Issue by kolontsov** [yandex/mocha-parallel-tests#88]
I don't see how I can implement bailing out immediately after first failing test. Even if I pass `--bail` (using `--opts filename.opts`), mocha-parallel-tests stops affected describe(), but continues to execute other suites.

I can modify bin-helper.js to do `customRunner.on('fail', function(e){ this.emit('end', 1); })`, but I'm not sure if it's intended way to do it.

**Comment by 1999** [comment]
Well you can see that tests are running in parallel and the problem is that at the moment when one of your tests fail you can have N already running tests. I guess that your approach should work, could you make a PR about it?

@k03mad look for this option, this is probably what you want to use instead of `mocha-steps`, uh?

**Comment by k03mad** [comment]
`--bail` breaks whole test run.
`mocha-steps` skips next `it`s in describe.
We use hooks for skip all `it`s in the test file.

**Comment by kolontsov** [comment]
ok, will make a PR.

> at the moment when one of your tests fail you can have N already running tests

I guess we just need to be sure that after() is correctly called for such tests?

**Comment by 1999** [comment]
Yes. And also check for exit code. If you need any help about writing tests ping me.

**Comment by 1999** [comment]
@kolontsov I have finally realised that `--bail` option can work different in mocha and mocha-parallel-tests. Here's the example:

```javascript
// test/async.js
describe('Test suite', () => {
    it('should end after 3 seconds', (done) => {
        setTimeout(done, 3000);
    });
});

// test/sync.js
describe('Test suite', () => {
    console.log(1);
    it('should end immediately', () => {
        console.log(2);
    });

    it('should fail', () => {
        throw new Error;
    });

    it('should end immediately', () => {});
    it('should end immediately', () => {});
});

// index.sh
mocha --bail --reporter json test/
mocha-parallel-tests --bail --reporter json test/
```

In first case stats.tests will be equal to 1, stats.suites is also 1, stats.failures is 1 and stats.passes is 0. This happens because `--bail` option prevents running of the next test file. But mocha-parallel-tests launches all tests in parallel which leads to different results (test/sync.js will be executed at the same time with test/async.js). So this is why `--bail` behaviour can differ between mocha and mocha-parallel-tests.
